CREATE TABLE USERS
(
    id               bigint generated by default as identity,
    name             VARCHAR(255) NOT NULL,
    age              INT          NOT NULL,
    profile_image_id INT,
    password         VARCHAR(255) NOT NULL,
    created_at DATE,
    updated_at DATE,
    primary key (id)
);

CREATE TABLE AUTH
(
    id         bigint generated by default as identity,
    user_id    INT       NOT NULL,
    token      VARCHAR(255) NOT NULL,
    primary key (id)
)