package study.designpattern.behavioral.interpreter.basic2;

import java.util.ArrayList;
import java.util.List;

class Client {

  // Running the Client class as application.
  public static void main(String[] args) throws Exception {
    //
    // Creating a collection of product objects.
    //
    List<Product> products = new ArrayList<Product>();
    products.add(new SalesProduct("PC1", "PC", "Product PC 1000", 1000));
    products.add(new SalesProduct("PC2", "PC", "Product PC 2000", 2000));
    products.add(new SalesProduct("PC3", "PC", "Product PC 3000", 3000));
    //
    products.add(new SalesProduct("TV1", "TV", "Product TV 1000", 1000));
    products.add(new SalesProduct("TV2", "TV", "Product TV 2000", 2000));
    products.add(new SalesProduct("TV3", "TV", "Product TV 3000", 3000));
    //
    // Representing the search expression:
    // ( (x and y) or (y and z and (not x)) )
    // by an AST (usually generated by a parser).
    //
    VarExpr x = new VarExpr("X");
    VarExpr y = new VarExpr("Y");
    VarExpr z = new VarExpr("Z");
    //
    Expression andExpr1 = new AndExpr();
    andExpr1.add(x);
    andExpr1.add(y);
    //
    Expression andExpr2 = new AndExpr();
    andExpr2.add(y);
    andExpr2.add(z);
    Expression notExpr = new NotExpr();
    notExpr.add(x);
    andExpr2.add(notExpr);
    //
    Expression expression = new OrExpr();
    expression.add(andExpr1);
    expression.add(andExpr2);
    //
    // For each product:
    // - specifying the search criteria dynamically and setting the context
    // - interpreting (evaluating) the AST (search expression).
    //
    Context context = new Context();
    for (Product p : products) {
      // For example, searching products with:
      // (group == "PC" and prize > 1000) or
      // (prize > 1000 and description containing "TV" and group is not "PC").
      // Setting VarExpr x,y,z in context to true or false.
      context.setVarExpr(x, p.getGroup() == "PC" ? true : false);
      context.setVarExpr(y, p.getPrice() > 1000 ? true : false);
      context.setVarExpr(z, p.getDescription().contains("TV") ? true : false);
      // Interpreting (evaluating) the AST (search expression).
      if (expression.evaluate(context)) {
        System.out.println("Product found: " + p.getDescription());
      }
    }
  }
}
